from enum import Enum

class EventType(Enum):
    # Vehicle events
    VEHICLE_CREATED = "VEHICLE_CREATED"
    VEHICLE_UPDATED = "VEHICLE_UPDATED"
    VEHICLE_DELETED = "VEHICLE_DELETED"
    VEHICLE_STATUS_CHANGED = "VEHICLE_STATUS_CHANGED"
    
    # Branch events
    BRANCH_CREATED = "BRANCH_CREATED"
    BRANCH_UPDATED = "BRANCH_UPDATED"
    BRANCH_DELETED = "BRANCH_DELETED"
    
    # Rental events
    RENTAL_CREATED = "RENTAL_CREATED"
    RENTAL_APPROVED = "RENTAL_APPROVED"
    RENTAL_REJECTED = "RENTAL_REJECTED"
    RENTAL_COMPLETED = "RENTAL_COMPLETED"
    
    # User events
    USER_CREATED = "USER_CREATED"
    USER_UPDATED = "USER_UPDATED"
    USER_DELETED = "USER_DELETED"